cc_binary(
    name = "scanner",
    copts = ["-Wall -g"],
    srcs = ["scanner.cc"],
    deps = ["//frontend/v1/scanner/state_machine", "//frontend/v1/scanner/token", "//frontend/v1/parser", "//abstract_syntax:print_visitor_v1"],
)
