cc_library(
  name = "frontend",
  copts = ["-Wall -g"],
  srcs = ["frontend.cc"],
  hdrs = ["frontend.h"],
  deps = ["//scanner/token", "//scanner/stateMachine", "//abstract_syntax", "//utility"],
  visibility = ["//visibility:public"],
)