cc_library(
  name = "frontend",
  copts = ["-Wall -g"],
  srcs = ["frontend.cc"],
  hdrs = ["frontend.h"],
  deps = ["//frontend/scanner/token", "//frontend/scanner/state_machine", "//abstract_syntax", "//utility"],
  visibility = ["//visibility:public"],
)
