bazel build intermediate_representation
bazel run v5_loop
bazel run v5_arithmetic
bazel run v5_assignables
bazel run v5_logicals
bazel run v5_integration
bazel run cfg_loop
bazel run cfg_arithmetic
bazel run cfg_assignables
bazel run cfg_logicals
bazel run cfg_integration
bazel run ssa_loop
bazel run ssa_arithmetic 
bazel run ssa_assignables
bazel run ssa_logicals
bazel run ssa_integration
