cc_test(
	name = "asm_generator_v1_test",
	srcs = ["asm_generator_v1_test.cc"],
	deps = [
             "@gtest//:main",
             "//backend:intermediate_representation"
        ],
	timeout = "short",
	size = "small",
)

cc_test(
	name = "asm_generator_v2_test",
	srcs = ["asm_generator_v2_test.cc"],
	deps = [
             "@gtest//:main",
             "//backend:intermediate_representation"
        ],
	timeout = "short",
	size = "small",
)

cc_test(
	name = "asm_generator_v3_test",
	srcs = ["asm_generator_v3_test.cc"],
	deps = [
             "@gtest//:main",
             "//backend:intermediate_representation"
        ],
	timeout = "short",
	size = "small",
)

cc_test(
	name = "integration_test",
	srcs = ["integration_test.cc"],
	deps = [
             "@gtest//:main",
             "//backend:intermediate_representation"
        ],
	timeout = "short",
	size = "small",
)
